### ISSUE TITLE
Graphics libraries

### ISSUE THREAD

**Issue by Squigss** [lao8n/battlestar#18]
Need to see if there are dependencies for libraries:
- G4P
- G4Ptool (or G4P Gui builder)
- peasycam

**Comment by lao8n** [comment]
Yeah, so it turns out you can just have the library in processing (I guess as you have already done, and then we can just call it in our SwarmWars.pde file. just need import g4p_controls.*; or whatever and then you can write your code. If you send me what you want to integrate I can help :)

**Comment by Squigss** [comment]
heya,

thanks for checking, sounds good. thats basically what i did. Let's hold
off integrating it for now as I need to check with Tim and Sonam what info
they need to retrieve from the user via this screen and it might change
quite a bit.

x
