### ISSUE TITLE
nullPointerException between fsmui - swarmSelect ui

### ISSUE THREAD

**Issue by timvan** [lao8n/battlestar#76]
Null pointer error when replays a game. occurs on both multiplayer & single player games.

Sometimes there is a rollover of information, i.e a algo has already been selected, when you get to the swarm select for the second time

ND pointed out it might be because the RHS/empty algos are being used

![Uploading image.png…]()

**Comment by Sonam363** [comment]
Not sure if I have found the same null pointer or another one but when you use the middle fsm from the ui i dont get the exception, its only on the triangle one (on the left).

**Comment by timvan** [comment]
![image](https://user-images.githubusercontent.com/14909281/58015642-ad9e8700-7af3-11e9-8daa-5fc0649c4809.png)

![image](https://user-images.githubusercontent.com/14909281/58015654-b4c59500-7af3-11e9-8f36-96b578964e65.png)


same error - 1player, after 3rd replay

**Comment by timvan** [comment]
with the above, the ghost was already highlighted as number 1 when the screen came on

**Comment by lao8n** [comment]
I think it is fixed 
* null pointer is because the swarm algorithms (e.g. 1 and 2 here) don't exist
* and the messed up fsm is because it isn't reset after game over.
